"""some changes

Revision ID: e358ed6e205d
Revises: 1f0e7327fb5e
Create Date: 2019-05-23 09:47:48.005534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e358ed6e205d'
down_revision = '1f0e7327fb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'file_url')
    # ### end Alembic commands ###
